from typing import TypedDict, List, Dict, Any, Optional

class DayGuardState(TypedDict):
    """
    Strongly-typed, serializable state definition for the DayGuard agent graph.
    Guarantees zero sensitive credentials, tokens, or API keys are stored in the state.
    """
    # User Input & Execution Mode
    user_request: str
    mock_scenario: Optional[str]
    demo_mode: bool                      # True = Deterministic Hackathon Demo Mode, False = Live Swytchcode APIs
    
    # Information Retrieval Phase Data
    user_context: Dict[str, Any]        # Notion profile context (commute, location, preferences)
    gmail_events: List[Dict[str, Any]]  # Gmail calendar events
    weather: Dict[str, Any]             # OpenWeather forecast & real-time metrics
    weather_data: Dict[str, Any]        # Alias for backward compatibility
    
    # Reasoning & Risk Evaluation Phase Data
    plan: List[str]                     # Execution steps generated by planner
    risk_level: str                     # Risk rating ("HIGH", "MEDIUM", "LOW")
    risk_reason: str                    # Natural language reasoning for risk rating
    reason: str                         # Alias for risk reasoning
    risk_assessment: Dict[str, Any]     # Detailed risk metadata dictionary
    
    # Decision & Action Execution Phase Data
    recommended_actions: List[Dict[str, Any]]  # Action items planned by decision engine
    selected_tools: List[str]            # Specific action tools selected for execution
    skipped_tools: List[str]             # Action tools explicitly skipped due to risk policy
    tools_used: List[str]                # All tools invoked during run
    actions_completed: List[Dict[str, Any]] # Audit log of completed actions
    actions_taken: List[Dict[str, Any]]  # Alias for backward compatibility
    executed_actions: List[Dict[str, Any]] # Alias for backward compatibility
    notifications_sent: List[Dict[str, Any]] # Delivered Slack alerts & Resend emails
    
    # UI Trace & Final Response
    trace_logs: List[Dict[str, Any]]    # Step-by-step execution timeline for UI trace
    final_response: str                 # Natural language summary presented to user

def sanitize_state_for_ui(state: Dict[str, Any]) -> Dict[str, Any]:
    """Helper function to strip sensitive tokens before rendering."""
    forbidden_keys = {"api_key", "token", "password", "secret", "credentials"}
    sanitized = {}
    for k, v in state.items():
        if any(fk in k.lower() for fk in forbidden_keys):
            sanitized[k] = "[REDACTED]"
        else:
            sanitized[k] = v
    return sanitized
